# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

language: python
git:
  depth: false
env:
  - PRE_COMMIT_HOME=$HOME/.cache/pre-commit
virtualenv:
  system_site_packages: false
jobs:
  fast_finish: true
  include:
    - python: 3.7
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py37" COVERAGE="false"
    - python: 3.8
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py38" COVERAGE="false"
    - python: 3.9
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py39" COVERAGE="true"
    - env: DISTRIB="conda" PYTHON_VERSION="3.8" COVERAGE="false"
install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "roberto@dealmeida.net"
  - git config --global user.name "Beto Dealmeida"
  # Useful information in case of debug
  - if [[ "$DISTRIB" == "conda" ]]; then conda info -a; fi
  - which tox
script:
  - tox -e build
  - tox
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
  - if [[ "$COVERAGE" == "true" ]]; then codecov || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
    - $HOME/.cache/pre-commit
