version: '3.8'

services:
  postgres:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      POSTGRES_PASSWORD: shillelagh123
      POSTGRES_USER: shillelagh
      POSTGRES_DB: shillelagh
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  ftp:
    image: stilliard/pure-ftpd:hardened
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: shillelagh
      FTP_USER_PASS: shillelagh123
      FTP_USER_HOME: /home/shillelagh
    volumes:
      - ./data:/home/shillelagh
    ports:
      - "2121:21"
      - "30000-30009:30000-30009"

  sftp:
    image: atmoz/sftp
    volumes:
      - ./data:/home/shillelagh
    environment:
      SFTP_USERS: "shillelagh:shillelagh123:1001"
    ports:
      - "2222:22"

volumes:
  db_data:
